AddCSLuaFile("cl_init.lua")
AddCSLuaFile("cl_view.lua")
AddCSLuaFile("cl_hud.lua")
AddCSLuaFile("cl_admin.lua")
AddCSLuaFile("cl_discord.lua")
AddCSLuaFile("cl_music.lua")
AddCSLuaFile("shared.lua")
AddCSLuaFile("sh_config.lua")
AddCSLuaFile("sh_teams.lua")
AddCSLuaFile("sh_compat.lua")
AddCSLuaFile("sh_movement.lua")
AddCSLuaFile("sh_round.lua")
AddCSLuaFile("cl_lobby.lua")
AddCSLuaFile("cl_scoreboard.lua")
AddCSLuaFile("cl_camera.lua")
AddCSLuaFile("cl_killfeed.lua")

include("shared.lua")
include("sv_player.lua")
include("sv_admin.lua")
include("sv_round.lua")
include("sv_bots.lua")

util.AddNetworkString("rf_music_cue")
util.AddNetworkString("rf_kill")
util.AddNetworkString("rf_feedclear")
