AddCSLuaFile("cl_init.lua")
AddCSLuaFile("cl_view.lua")
AddCSLuaFile("cl_hud.lua")
AddCSLuaFile("cl_admin.lua")
AddCSLuaFile("cl_discord.lua")
AddCSLuaFile("cl_music.lua")
AddCSLuaFile("shared.lua")
AddCSLuaFile("sh_config.lua")
AddCSLuaFile("sh_teams.lua")
AddCSLuaFile("sh_compat.lua")
AddCSLuaFile("sh_movement.lua")

include("shared.lua")
include("sv_player.lua")
include("sv_admin.lua")

util.AddNetworkString("rf_music_cue")
